version: '3'

volumes:
  test_data:

services:
  test-db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - test_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - 5005:80
    depends_on:
      - test-db
  tg_bot:
    build: ./
    env_file: .env
    depends_on:
      - test-db